### ISSUE TITLE
Create a script to manage mysql connection and use it in all 4 php files

### ISSUE THREAD

**Issue by lantushenkoao** [ProPavelK/datagenscript#1]
Create a fille called db_connection.php (for example) and move all mysql configuration settings (such as username, password, server name, etc). Then use this file in all 4 existing php scripts.

**Comment by ProPavelK** [comment]
Added configuration file for the project - app__configuration.php with all the settings such as server and database parameters also database tables etc). Configuration file is in use by all 4 existing php scripts.
