### ISSUE TITLE
Enhance app__delete_db_tables.php

### ISSUE THREAD

**Issue by lantushenkoao** [ProPavelK/datagenscript#2]
At the moment this script drops all tables when you open it in browser, this is quite dangerous.
Instead, please create a page that will display html button labeled Delete. When user clicks on the button, a POST http request is made and all tables are deleted.

**Comment by ProPavelK** [comment]
Now the script that deletes database tables with all the data has the html template with button labeled 'Delete' - app__delete_db_tables. When user clicks on the button, a POST http request is made and all tables are removed. PHP Ajax form has the validation - input name cannot be empty. Form processor file - app__delete_dbtbl_process.php
